name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: MacOS
    runs-on: macos-13
    strategy:
      fail-fast: true
      matrix:
        xcode: ['15.0']
        config: ['debug']
    steps:
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.6"
      - name: Swift Version
        run: swift --version
      - name: Run ${{ matrix.xcode }} Tests
        run: make CONFIG=${{ matrix.config }} test-library

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-linux
