name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS
    runs-on: macos-14
    strategy:
      matrix:
        config: ['debug', 'release']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3.1
        run: sudo xcode-select -s /Applications/Xcode_16.2.0.app
      - name: Swift Version
        run: swift --version
      - name: Run tests
        run: make test-swift
      - name: Build platforms ${{ matrix.config }}
        run: CONFIG=${{ matrix.config }} make build-all-platforms

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-swift

#   wasm:
#     name: Wasm
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         include:
#           - { toolchain: wasm-5.7.1-RELEASE }
#     steps:
#       - uses: actions/checkout@v3
#       - run: echo "${{ matrix.toolchain }}" > .swift-version
#       - uses: swiftwasm/swiftwasm-action@v5.7
#         with:
#           shell-action: carton test --environment node
#
#   windows:
#     name: Windows
#     runs-on: windows-latest
#     steps:
#       - uses: compnerd/gha-setup-swift@main
#         with:
#           branch: swift-5.8-release
#           tag: 5.8-RELEASE
#       - uses: actions/checkout@v3
#       - name: Run tests
#         run: swift test
#       - name: Run tests (release)
#         run: swift test -c release
