name: CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - '*'
jobs:
  build:
    name: MacOS
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v2
    - name: Run swift tests
      run: make test
      
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
