name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3.1
        run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      - name: Swift Version
        run: swift --version
      - name: Run tests
        run: make test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-swift
